sensors:
  # - camera_0_pointcloud
  - camera_1_pointcloud
  - 3d_lidar_pointcloud
# camera_0_pointcloud:
#   sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
#   point_cloud_topic: camera_0/points
#   filtered_cloud_topic: filtered_cloud
#   max_range: 5.0
#   max_update_rate: 2.0
#   padding_offset: 0.002
#   padding_scale: 1.0
#   point_subsample: 1
camera_1_pointcloud:
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  point_cloud_topic: <robot_prefix>camera_1/points
  filtered_cloud_topic: filtered_cloud
  max_range: 5.0
  max_update_rate: 2.0
  padding_offset: 0.002
  padding_scale: 1.0
  point_subsample: 1
# 3d_lidar_pointcloud:
#   sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
#   point_cloud_topic: /scan_cloud
#   filtered_cloud_topic: filtered_cloud
#   max_range: 5.0
#   max_update_rate: 2.0
#   padding_offset: 0.002
#   padding_scale: 1.0
#   point_subsample: 1