# This template defines velocity and acceleration limits for all robot joints.
# Template variable <robot_prefix> is replaced at launch time.

default_velocity_scaling_factor: 0.50
default_acceleration_scaling_factor: 0.50

joint_limits:
  <robot_prefix>joint_1:
    has_velocity_limits: true
    max_velocity: 1.05
    has_acceleration_limits: true
    max_acceleration: 1.0
  <robot_prefix>joint_2:
    has_velocity_limits: true
    max_velocity: 1.05
    has_acceleration_limits: true
    max_acceleration: 1.0
  <robot_prefix>joint_3:
    has_velocity_limits: true
    max_velocity: 1.05
    has_acceleration_limits: true
    max_acceleration: 1.0
  <robot_prefix>joint_4:
    has_velocity_limits: true
    max_velocity: 1.73
    has_acceleration_limits: true
    max_acceleration: 1.0
  <robot_prefix>joint_5:
    has_velocity_limits: true
    max_velocity: 1.73
    has_acceleration_limits: true
    max_acceleration: 1.0
  <robot_prefix>joint_6:
    has_velocity_limits: true
    max_velocity: 1.73
    has_acceleration_limits: true
    max_acceleration: 1.0